version: '3'
services:

    db:
        build:
            context: ./db
        restart: always
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted

    frontend:
        restart: always
        build:
            context: ./Frontend
            dockerfile: Dockerfile.dev
        environment:
            - NODE_ENV=development
            - PORT=3000
        ports:
            - '3000:3000'

        volumes:
            - ./Frontend:/root/frontend:cached
            

    backend:
        restart: always
        depends_on:
            - "db"
        command: sh -c 'RUN curl -OL https://raw.githubusercontent.com/mrako/wait-for/master/wait-for && chmod +x && ./wait-for db:3306 -- python -m flask run -h 0.0.0.0 -p 5000'
        build:
            context: ./Backend
            dockerfile: Dockerfile.dev
        ports:
            - '5000:5000'
        volumes:
            - "./Backend:/root/backend:cached"

    

