version: '3'
services:

    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=squizz_app     # So you don't have to use root, but you can if you like
            - MYSQL_USER:=squizz
            # You can use whatever password you like
            - MYSQL_PASSWORD=squizz
            # Password for root access
            - MYSQL_ROOT_PASSWORD=squizz
            - MYSQL_ROOT_HOST=%
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - "./MysqlConf:/etc/mysql/conf.d"
            - ./db:/docker-entrypoint-initdb.d

    frontend:
        build:
            context: ./Frontend
            dockerfile: Dockerfile-Frontend
       
        command: sh -c "npm install && npm install ip --save-dev  &&npm run start"
        environment:
            - NODE_ENV=development
            - PORT=3000
        ports:
            - '3000:3000'
        
        working_dir: /root/frontend
        volumes:
            - ./Frontend:/root/frontend:cached
        expose:
            # Opens port 3306 on the container
            - '3000'
           
            # Where our data will be persisted
            

    backend:
  
        build:
            context: ./Backend
            dockerfile: Dockerfile-Backend

        environment:
            - BASE_URL=https://api.squizz.com/rest/1
            - ORG_ID=11EA64D91C6E8F70A23EB6800B5BCB6D
            - API_ORG_KEY=3a62ea5aa2d8845a72dd030369dd571d5123567f70fa76b5bc3bcdf103e3307cc52b01030230c4f2807b44f88ce0052e91f3b7550341f38fe6544d02abfd7d87
            - API_ORG_PW=Team21_22
            - MYSQL_DATABASE=squizz_app
            # So you don't have to use root, but you can if you like
            - MYSQL_USERNAME=root
            # You can use whatever password you like
            - MYSQL_PASSWORD=squizz
            - MYSQL_URI=db
            # Password for root access
            - MYSQL_ROOT_PASSWORD=squizz

        command: sh -c "pip install -r requirements.txt && python -m flask run -h 0.0.0.0 -p 5000"
        ports:
            - '5000:5000'
        working_dir: /root/backend
        volumes:
            - "./Backend:/root/backend:cached"

    

