version: '3'
services:
    frontend:
        build: ./Frontend
        command: sh -c "npm install && npm run start -- --host=0.0.0.0"
        environment:
            - NODE_ENV=development
            - PORT=3000
        ports:
            - '3001:3000'
        working_dir: /root/frontend
        volumes:
            - ./Frontend:/root/frontend:cached
        expose:
            # Opens port 3306 on the container
            - '3000'
            # Where our data will be persisted
            

    backend:
  
        build: ./Backend
        environment:
            - BASE_URL=https://api.squizz.com/rest/1
            - ORG_ID=11EA64D91C6E8F70A23EB6800B5BCB6D
            - API_ORG_KEY=3a62ea5aa2d8845a72dd030369dd571d5123567f70fa76b5bc3bcdf103e3307cc52b01030230c4f2807b44f88ce0052e91f3b7550341f38fe6544d02abfd7d87
            - API_ORG_PW=Team21_22
            - MYSQL_DATABASE=db
            # So you don't have to use root, but you can if you like
            - MYSQL_USERNAME=user
            # You can use whatever password you like
            - MYSQL_PASSWORD=password
            - MYSQL_URI=localhost:3306
            # Password for root access
            - MYSQL_ROOT_PASSWORD=password

        command: sh -c "pip install -r requirements.txt && python -m flask run -h 0.0.0.0 -p 5000"
        ports:
            - '5001:5000'
        working_dir: /root/backend
        volumes:
            - "./Backend:/root/backend:cached"

    
    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE=db      # So you don't have to use root, but you can if you like
            - MYSQL_USER:=user
            # You can use whatever password you like
            - MYSQL_PASSWORD=password
            # Password for root access
            - MYSQL_ROOT_PASSWORD=password
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3307:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - "./MysqlConf:/etc/mysql/conf.d"
